version: '3'

networks:
    trellis:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        networks:
            - trellis