version: '3'

networks:
    trellis:

services:
    redis:
        image: redis:alpine
        command: redis-server
        ports:
            - 6379:6379
        networks:
            - trellis
    mongo:
        image: mongo
        ports:
            - 27018:27017
            - 27017:27017
        networks:
            - trellis
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        networks:
            - trellis