version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  job1:
    working_directory: ~/project/repo
    resource_class: arm.medium
    machine:
        image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: yarn
      - run: docker-compose up -d
      - run: yarn prisma db push

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - job1